#include "gds_opcode.h"

const char *gds_opcode_to_string(gds_opcode_t opcode) {
    switch (opcode) {
    case SCRIPT_CMD_FadeIn:
        return "FadeIn";
    case SCRIPT_CMD_FadeInOnly:
        return "FadeInOnly";
    case SCRIPT_CMD_FadeInOnlySub:
        return "FadeInOnlySub";
    case SCRIPT_CMD_FadeInOnlyMain:
        return "FadeInOnlyMain";
    case SCRIPT_CMD_FadeOut:
        return "FadeOut";
    case SCRIPT_CMD_FadeOutOnly:
        return "FadeOutOnly";
    case SCRIPT_CMD_FadeOutOnlySub:
        return "FadeOutOnlySub";
    case SCRIPT_CMD_FadeOutOnlyMain:
        return "FadeOutOnlyMain";
    case SCRIPT_CMD_WaitPenTouch:
        return "WaitPenTouch";
    case SCRIPT_CMD_WaitInput:
        return "WaitInput";
    case SCRIPT_CMD_LoadBG:
        return "LoadBG";
    case SCRIPT_CMD_LoadSubBG:
        return "LoadSubBG";
    case SCRIPT_CMD_WaitVSyncOrPenTouch:
        return "WaitVSyncOrPenTouch";
    case SCRIPT_CMD_UnloadAllGfx:
        return "UnloadAllGfx";
    case SCRIPT_CMD_VSyncProcess:
        return "VSyncProcess";
    case SCRIPT_CMD_PlaySound:
        return "PlaySound";
    case SCRIPT_CMD_PlayBGM:
        return "PlayBGM";
    case SCRIPT_CMD_IF:
        return "IF";
    case SCRIPT_CMD_CheckRoomNumber:
        return "CheckRoomNumber";
    case SCRIPT_CMD_Loop:
        return "Loop";
    case SCRIPT_CMD_WHILE:
        return "WHILE";
    case SCRIPT_CMD_ELSEIF:
        return "ELSEIF";
    case SCRIPT_CMD_ELSE:
        return "ELSE";
    case SCRIPT_CMD_PressingStart:
        return "PressingStart";
    case SCRIPT_CMD_TRUE:
        return "TRUE";
    case SCRIPT_CMD_FALSE:
        return "FALSE";
    case SCRIPT_CMD_CreateQuestion:
        return "CreateQuestion";
    case SCRIPT_CMD_AddHints:
        return "AddHints";
    case SCRIPT_CMD_AddButtons:
        return "AddButtons";
    case SCRIPT_CMD_SetCorrect:
        return "SetCorrect";
    case SCRIPT_CMD_SetQuestionEndBG:
        return "SetQuestionEndBG";
    case SCRIPT_CMD_AddHint:
        return "AddHint";
    case SCRIPT_CMD_AddQuestionButton:
        return "AddQuestionButton";
    case SCRIPT_CMD_AddExit:
        return "AddExit";
    case SCRIPT_CMD_AddChr:
        return "AddChr";
    case SCRIPT_CMD_SetNumberAnswer:
        return "SetNumberAnswer";
    case SCRIPT_CMD_AddCoin:
        return "AddCoin";
    case SCRIPT_CMD_AddCoinSolution:
        return "AddCoinSolution";
    case SCRIPT_CMD_SetNumTouch:
        return "SetNumTouch";
    case SCRIPT_CMD_GridAddBlock:
        return "GridAddBlock";
    case SCRIPT_CMD_GridAddLetter:
        return "GridAddLetter";
    case SCRIPT_CMD_AddMatch:
        return "AddMatch";
    case SCRIPT_CMD_AddMatchSolution:
        return "AddMatchSolution";
    case SCRIPT_CMD_SetQuestionEvent:
        return "SetQuestionEvent";
    case SCRIPT_CMD_AddWeights:
        return "AddWeights";
    case SCRIPT_CMD_RandomLightWeight:
        return "RandomLightWeight";
    case SCRIPT_CMD_RandomHeavyWeight:
        return "RandomHeavyWeight";
    case SCRIPT_CMD_RandomLightOrHeavyWeight:
        return "RandomLightOrHeavyWeight";
    case SCRIPT_CMD_AddChicken:
        return "AddChicken";
    case SCRIPT_CMD_AddWolf:
        return "AddWolf";
    case SCRIPT_CMD_NewShape:
        return "NewShape";
    case SCRIPT_CMD_AddVertex:
        return "AddVertex";
    case SCRIPT_CMD_AddTriangle:
        return "AddTriangle";
    case SCRIPT_CMD_SetShapePosition:
        return "SetShapePosition";
    case SCRIPT_CMD_SetShapeRotation:
        return "SetShapeRotation";
    case SCRIPT_CMD_SetShapeSolutionPosition:
        return "SetShapeSolutionPosition";
    case SCRIPT_CMD_SetShapeSolutionRotation:
        return "SetShapeSolutionRotation";
    case SCRIPT_CMD_AddCup:
        return "AddCup";
    case SCRIPT_CMD_SetBoard:
        return "SetBoard";
    case SCRIPT_CMD_AddQueens:
        return "AddQueens";
    case SCRIPT_CMD_AddGoldQueen:
        return "AddGoldQueen";
    case SCRIPT_CMD_SetQueenCheckMode:
        return "SetQueenCheckMode";
    case SCRIPT_CMD_SetFillPos:
        return "SetFillPos";
    case SCRIPT_CMD_AddInPoint:
        return "AddInPoint";
    case SCRIPT_CMD_AddOutPoint:
        return "AddOutPoint";
    case SCRIPT_CMD_SetFontUserColor:
        return "SetFontUserColor";
    case SCRIPT_CMD_AddTextObj:
        return "AddTextObj";
    case SCRIPT_CMD_TextWindow:
        return "TextWindow";
    case SCRIPT_CMD_SetTextWindowLeft:
        return "SetTextWindowLeft";
    case SCRIPT_CMD_SetTextWindowRight:
        return "SetTextWindowRight";
    case SCRIPT_CMD_SetWinNum:
        return "SetWinNum";
    case SCRIPT_CMD_SetCurrentQuestion:
        return "SetCurrentQuestion";
    case SCRIPT_CMD_FoundQuestion:
        return "FoundQuestion";
    case SCRIPT_CMD_EventModeStart:
        return "EventModeStart";
    case SCRIPT_CMD_EventModeFinish:
        return "EventModeFinish";
    case SCRIPT_CMD_FailQuestion:
        return "FailQuestion";
    case SCRIPT_CMD_CorrectQuestion:
        return "CorrectQuestion";
    case SCRIPT_CMD_SolvedQuestion:
        return "SolvedQuestion";
    case SCRIPT_CMD_ExitScript:
        return "ExitScript";
    case SCRIPT_CMD_AddEvent:
        return "AddEvent";
    case SCRIPT_CMD_SetGameMode:
        return "SetGameMode";
    case SCRIPT_CMD_SetQuestionEndGameMode:
        return "SetQuestionEndGameMode";
    case SCRIPT_CMD_SetCurrentRoom:
        return "SetCurrentRoom";
    case SCRIPT_CMD_CorrectQuestionN:
        return "CorrectQuestionN";
    case SCRIPT_CMD_SetEventFinished:
        return "SetEventFinished";
    case SCRIPT_CMD_DoPrizeScreen:
        return "DoPrizeScreen";
    case SCRIPT_CMD_DoStockScreen:
        return "DoStockScreen";
    case SCRIPT_CMD_ViewedEvent:
        return "ViewedEvent";
    case SCRIPT_CMD_PlayBridgeSound:
        return "PlayBridgeSound";
    case SCRIPT_CMD_SetMap:
        return "SetMap";
    case SCRIPT_CMD_SetExitSound:
        return "SetExitSound";
    case SCRIPT_CMD_AddBGObject:
        return "AddBGObject";
    case SCRIPT_CMD_AddOnOffButton:
        return "AddOnOffButton";
    case SCRIPT_CMD_SetTarget:
        return "SetTarget";
    case SCRIPT_CMD_UnloadMainGfx:
        return "UnloadMainGfx";
    case SCRIPT_CMD_SetCurrentEvent:
        return "SetCurrentEvent";
    case SCRIPT_CMD_DoSaveScreen:
        return "DoSaveScreen";
    case SCRIPT_CMD_SetStoryFlag:
        return "SetStoryFlag";
    case SCRIPT_CMD_StoryFlag:
        return "StoryFlag";
    case SCRIPT_CMD_ForceTutorial:
        return "ForceTutorial";
    case SCRIPT_CMD_SetTextWindowCenter:
        return "SetTextWindowCenter";
    case SCRIPT_CMD_PuzzleSolverLayton:
        return "PuzzleSolverLayton";
    case SCRIPT_CMD_PuzzleSolverLuke:
        return "PuzzleSolverLuke";
    case SCRIPT_CMD_AddHintCoin:
        return "AddHintCoin";
    case SCRIPT_CMD_FadeOutBGM:
        return "FadeOutBGM";
    case SCRIPT_CMD_FadeInBGM:
        return "FadeInBGM";
    case SCRIPT_CMD_WaitFrame:
        return "WaitFrame";
    case SCRIPT_CMD_AddSprite:
        return "AddSprite";
    case SCRIPT_CMD_AddSpriteChild:
        return "AddSpriteChild";
    case SCRIPT_CMD_SetSpriteAnimation:
        return "SetSpriteAnimation";
    case SCRIPT_CMD_SetSpriteAnimationChild:
        return "SetSpriteAnimationChild";
    case SCRIPT_CMD_SetSpritePosition:
        return "SetSpritePosition";
    case SCRIPT_CMD_SpriteOn:
        return "SpriteOn";
    case SCRIPT_CMD_SpriteOff:
        return "SpriteOff";
    case SCRIPT_CMD_AddTile:
        return "AddTile";
    case SCRIPT_CMD_AddPoint:
        return "AddPoint";
    case SCRIPT_CMD_AddTileSolution:
        return "AddTileSolution";
    case SCRIPT_CMD_SetNumSolution:
        return "SetNumSolution";
    case SCRIPT_CMD_NumQuestionsSolved:
        return "NumQuestionsSolved";
    case SCRIPT_CMD_SetSpriteFade:
        return "SetSpriteFade";
    case SCRIPT_CMD_SetSpriteAlpha:
        return "SetSpriteAlpha";
    case SCRIPT_CMD_DrawFrames:
        return "DrawFrames";
    case SCRIPT_CMD_ModifyBGPal:
        return "ModifyBGPal";
    case SCRIPT_CMD_ModifySubBGPal:
        return "ModifySubBGPal";
    case SCRIPT_CMD_FreeEventAniMemory:
        return "FreeEventAniMemory";
    case SCRIPT_CMD_AddSubSprite:
        return "AddSubSprite";
    case SCRIPT_CMD_SetSubSpriteAnimation:
        return "SetSubSpriteAnimation";
    case SCRIPT_CMD_SetSubSpritePosition:
        return "SetSubSpritePosition";
    case SCRIPT_CMD_SubSpriteOn:
        return "SubSpriteOn";
    case SCRIPT_CMD_SubSpriteOff:
        return "SubSpriteOff";
    case SCRIPT_CMD_AddCoinType:
        return "AddCoinType";
    case SCRIPT_CMD_AddCoinSolutionType:
        return "AddCoinSolutionType";
    case SCRIPT_CMD_AddItem:
        return "AddItem";
    case SCRIPT_CMD_CheckItem:
        return "CheckItem";
    case SCRIPT_CMD_ShakeBG:
        return "ShakeBG";
    case SCRIPT_CMD_ShakeSubBG:
        return "ShakeSubBG";
    case SCRIPT_CMD_AddMan:
        return "AddMan";
    case SCRIPT_CMD_AddCabbage:
        return "AddCabbage";
    case SCRIPT_CMD_AddSheep:
        return "AddSheep";
    case SCRIPT_CMD_SetRiverCrossMode:
        return "SetRiverCrossMode";
    case SCRIPT_CMD_BitFlag:
        return "BitFlag";
    case SCRIPT_CMD_SetBitFlag:
        return "SetBitFlag";
    case SCRIPT_CMD_SetSpriteShake:
        return "SetSpriteShake";
    case SCRIPT_CMD_SetSpriteState:
        return "SetSpriteState";
    case SCRIPT_CMD_SetSpriteTargetPosition:
        return "SetSpriteTargetPosition";
    case SCRIPT_CMD_SetSpriteSpeed:
        return "SetSpriteSpeed";
    case SCRIPT_CMD_SetSubSpriteShake:
        return "SetSubSpriteShake";
    case SCRIPT_CMD_SetSubSpriteState:
        return "SetSubSpriteState";
    case SCRIPT_CMD_SetSubSpriteTargetPosition:
        return "SetSubSpriteTargetPosition";
    case SCRIPT_CMD_SetSubSpriteSpeed:
        return "SetSubSpriteSpeed";
    case SCRIPT_CMD_SetSpriteType:
        return "SetSpriteType";
    case SCRIPT_CMD_TextWindowK:
        return "TextWindowK";
    case SCRIPT_CMD_TextWindowR:
        return "TextWindowR";
    case SCRIPT_CMD_TextWindowL:
        return "TextWindowL";
    case SCRIPT_CMD_TextWindowM:
        return "TextWindowM";
    case SCRIPT_CMD_TextWindowKR:
        return "TextWindowKR";
    case SCRIPT_CMD_TextWindowKL:
        return "TextWindowKL";
    case SCRIPT_CMD_SetMemoFlag:
        return "SetMemoFlag";
    case SCRIPT_CMD_SetGridTypeRange:
        return "SetGridTypeRange";
    case SCRIPT_CMD_AddTouchPoint:
        return "AddTouchPoint";
    case SCRIPT_CMD_AddCheckLine:
        return "AddCheckLine";
    case SCRIPT_CMD_EnableNaname:
        return "EnableNaname";
    case SCRIPT_CMD_SetGridPosition:
        return "SetGridPosition";
    case SCRIPT_CMD_SetGridSize:
        return "SetGridSize";
    case SCRIPT_CMD_SetBlockSize:
        return "SetBlockSize";
    case SCRIPT_CMD_AddBlock:
        return "AddBlock";
    case SCRIPT_CMD_SetKatakanaAnswer:
        return "SetKatakanaAnswer";
    case SCRIPT_CMD_SetInputType:
        return "SetInputType";
    case SCRIPT_CMD_SetAlphabetAnswer:
        return "SetAlphabetAnswer";
    case SCRIPT_CMD_SetType:
        return "SetType";
    case SCRIPT_CMD_OnHintMedal:
        return "OnHintMedal";
    case SCRIPT_CMD_SetLineColor:
        return "SetLineColor";
    case SCRIPT_CMD_SetPenColor:
        return "SetPenColor";
    case SCRIPT_CMD_LoadBGSetFadeIn:
        return "LoadBGSetFadeIn";
    case SCRIPT_CMD_DoSpriteFadeIn:
        return "DoSpriteFadeIn";
    case SCRIPT_CMD_DoSpriteFadeInFast:
        return "DoSpriteFadeInFast";
    case SCRIPT_CMD_AddShapeSolutionType:
        return "AddShapeSolutionType";
    case SCRIPT_CMD_SetShapeType:
        return "SetShapeType";
    case SCRIPT_CMD_DoSpriteFadeOut:
        return "DoSpriteFadeOut";
    case SCRIPT_CMD_SetSpriteFlip:
        return "SetSpriteFlip";
    case SCRIPT_CMD_AddRotateBox:
        return "AddRotateBox";
    case SCRIPT_CMD_AddStoryScript:
        return "AddStoryScript";
    case SCRIPT_CMD_SetQuestionSolved:
        return "SetQuestionSolved";
    case SCRIPT_CMD_SetEventViewed:
        return "SetEventViewed";
    case SCRIPT_CMD_SetSingleNumberAnswer:
        return "SetSingleNumberAnswer";
    case SCRIPT_CMD_SetPuzzleTitle:
        return "SetPuzzleTitle";
    case SCRIPT_CMD_SetShapeSolutionMirror:
        return "SetShapeSolutionMirror";
    case SCRIPT_CMD_AddLaytonFurniture:
        return "AddLaytonFurniture";
    case SCRIPT_CMD_AddLukeFurniture:
        return "AddLukeFurniture";
    case SCRIPT_CMD_DisableResetButton:
        return "DisableResetButton";
    case SCRIPT_CMD_SetLiquidColor:
        return "SetLiquidColor";
    case SCRIPT_CMD_SetQuestionFailBG:
        return "SetQuestionFailBG";
    case SCRIPT_CMD_PenTouched:
        return "PenTouched";
    case SCRIPT_CMD_AddDogPart:
        return "AddDogPart";
    case SCRIPT_CMD_SetQuestionCarot:
        return "SetQuestionCarot";
    case SCRIPT_CMD_DoDogItemScreen:
        return "DoDogItemScreen";
    case SCRIPT_CMD_DoJigsawScreen:
        return "DoJigsawScreen";
    case SCRIPT_CMD_AddLaytonItemText:
        return "AddLaytonItemText";
    case SCRIPT_CMD_AddLaytonItemTextParent:
        return "AddLaytonItemTextParent";
    case SCRIPT_CMD_AddLukeItemText:
        return "AddLukeItemText";
    case SCRIPT_CMD_AddLukeItemTextParent:
        return "AddLukeItemTextParent";
    case SCRIPT_CMD_AddLaytonHint:
        return "AddLaytonHint";
    case SCRIPT_CMD_AddLukeHint:
        return "AddLukeHint";
    case SCRIPT_CMD_DoFurnitureScreen:
        return "DoFurnitureScreen";
    case SCRIPT_CMD_TextWindowKM:
        return "TextWindowKM";
    case SCRIPT_CMD_RemoveItem:
        return "RemoveItem";
    case SCRIPT_CMD_SetItemName:
        return "SetItemName";
    case SCRIPT_CMD_SetTraceCorrectZone:
        return "SetTraceCorrectZone";
    case SCRIPT_CMD_AddDogEvent:
        return "AddDogEvent";
    case SCRIPT_CMD_AddDogCoin:
        return "AddDogCoin";
    case SCRIPT_CMD_SetMovieNum:
        return "SetMovieNum";
    case SCRIPT_CMD_AddTracePoint:
        return "AddTracePoint";
    case SCRIPT_CMD_ChoiceWindow3:
        return "ChoiceWindow3";
    case SCRIPT_CMD_SetChoiceText1:
        return "SetChoiceText1";
    case SCRIPT_CMD_SetChoiceText2:
        return "SetChoiceText2";
    case SCRIPT_CMD_SetChoiceText3:
        return "SetChoiceText3";
    case SCRIPT_CMD_SetChoiceQuestion:
        return "SetChoiceQuestion";
    case SCRIPT_CMD_OnChoice:
        return "OnChoice";
    case SCRIPT_CMD_ChoiceWindow2:
        return "ChoiceWindow2";
    case SCRIPT_CMD_SetQuestionInfo:
        return "SetQuestionInfo";
    case SCRIPT_CMD_PlayMovieDual:
        return "PlayMovieDual";
    case SCRIPT_CMD_SaveTextureMemoryState:
        return "SaveTextureMemoryState";
    case SCRIPT_CMD_SetButtonAnswerWifi:
        return "SetButtonAnswerWifi";
    case SCRIPT_CMD_SetNumberAnswerWifi:
        return "SetNumberAnswerWifi";
    case SCRIPT_CMD_SetLetterAnswerWifi:
        return "SetLetterAnswerWifi";
    case SCRIPT_CMD_SetHiraganaAnswerWifi:
        return "SetHiraganaAnswerWifi";
    case SCRIPT_CMD_SetKatakanaAnswerWifi:
        return "SetKatakanaAnswerWifi";
    case SCRIPT_CMD_AddBabaQuestion:
        return "AddBabaQuestion";
    case SCRIPT_CMD_SetBabaParam:
        return "SetBabaParam";
    case SCRIPT_CMD_LoadBabaData:
        return "LoadBabaData";
    case SCRIPT_CMD_DoBabaAddScreen:
        return "DoBabaAddScreen";
    case SCRIPT_CMD_DoHukamaruAddScreen:
        return "DoHukamaruAddScreen";
    case SCRIPT_CMD_SetAraSujiEventNumber:
        return "SetAraSujiEventNumber";
    case SCRIPT_CMD_DoAraSujiEvent:
        return "DoAraSujiEvent";
    case SCRIPT_CMD_PressingX:
        return "PressingX";
    case SCRIPT_CMD_FadeToVolumeBGM:
        return "FadeToVolumeBGM";
    case SCRIPT_CMD_LoadPlayBGM:
        return "LoadPlayBGM";
    case SCRIPT_CMD_LoadOtherSoundGroup:
        return "LoadOtherSoundGroup";
    case SCRIPT_CMD_PlayBGMWait:
        return "PlayBGMWait";
    case SCRIPT_CMD_FadeBGMWait:
        return "FadeBGMWait";
    case SCRIPT_CMD_PlayMovieSound:
        return "PlayMovieSound";
    case SCRIPT_CMD_SetMaxDist:
        return "SetMaxDist";
    case SCRIPT_CMD_PlaySoundDirect:
        return "PlaySoundDirect";
    case SCRIPT_CMD_LoadEventSoundGroup:
        return "LoadEventSoundGroup";
    case SCRIPT_CMD_SetChangeAnswerKomoji:
        return "SetChangeAnswerKomoji";
    case SCRIPT_CMD_NoTutorial:
        return "NoTutorial";
    case SCRIPT_CMD_FadeOutBGMScript:
        return "FadeOutBGMScript";
    case SCRIPT_CMD_FadeInBGMScript:
        return "FadeInBGMScript";
    case SCRIPT_CMD_FadeOutBGMQuick:
        return "FadeOutBGMQuick";
    case SCRIPT_CMD_SetAnswerBox:
        return "SetAnswerBox";
    case SCRIPT_CMD_SetAnswer:
        return "SetAnswer";
    case SCRIPT_CMD_SetDrawInputBG:
        return "SetDrawInputBG";
    case SCRIPT_CMD_SetSubTitle:
        return "SetSubTitle";
    case SCRIPT_CMD_SetMovie:
        return "SetMovie";
    case SCRIPT_CMD_SetFullScreen:
        return "SetFullScreen";
    case SCRIPT_CMD_DoNoChargedScreen:
        return "DoNoChargedScreen";
    case SCRIPT_CMD_SetLaytonChallenge:
        return "SetLaytonChallenge";
    case SCRIPT_CMD_DoDownload:
        return "DoDownload";
    case SCRIPT_CMD_SetBandType:
        return "SetBandType";
    case SCRIPT_CMD_AddSecretCoin:
        return "AddSecretCoin";
    case SCRIPT_CMD_OnSecretMedal:
        return "OnSecretMedal";
    case SCRIPT_CMD_SetCharmPoint:
        return "SetCharmPoint";
    case SCRIPT_CMD_SetL5iDPoint:
        return "SetL5iDPoint";
    case SCRIPT_CMD_SetTopSecretPoint:
        return "SetTopSecretPoint";
    default:
        return "UNKNOWN_OPCODE";
    }
}

bool gds_is_valid_opcode(gds_opcode_t opcode) {
    if (opcode > SCRIPT_CMD_Invalid && opcode < SCRIPT_CMD_MAX) {
        return true;
    }
    return false;
}
